### ISSUE TITLE
Explain processing logic for uploading documents 

### ISSUE THREAD

**Issue by mrwunderbar666** [JBGruber/amcat-book#1]
From my tests, I can infer that AmCAT somehow notices whether a document is new or not. When I upload the exact same document again and again, AmCAT will not create duplicated documents (which is the desired behaviour in my opinion).

But I think it would be great to explain how AmCAT decides whether a document is new or not, and maybe how to force AmCAT not to deduplicate.

**Comment by JBGruber** [comment]
Good point! 

FYI: This is a side effect of the ID creation. When a document contains no `_id` field, it is created from the hash of the document (all fields). If you upload the same document, again, this will create the same hash and *overwrite* the document in the index. It looks as if the duplicate is automatically removed while in reality it is replaced by the same data. You can test this by giving the same doc different IDs and then replace one of the entries with a different doc, but same ID.
